USE MetalurgicaWeb;
GO
CREATE TABLE Rol(
	RolId INT IDENTITY(1,1) PRIMARY KEY,
	Nombre NVARCHAR(50) NOT NULL
);

CREATE TABLE Usuario(
	UsuarioId INT IDENTITY(1,1) PRIMARY KEY,
	RolId INT NOT NULL,
	Nombre NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	ContraseñaHash NVARCHAR(255) NOT NULL,
	Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Cliente(
	ClienteId INT IDENTITY(1,1) PRIMARY KEY,
	Cuit CHAR(11) NOT NULL,
	Email NVARCHAR(100),
	Telefono NVARCHAR(20),
	Direccion NVARCHAR(150),
	RazonSocial NVARCHAR(150) NOT NULL,
	Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Producto(
	ProductoId INT IDENTITY(1,1) PRIMARY KEY,
	Nombre NVARCHAR(100) NOT NULL,
	Descripcion NVARCHAR(255),
	Precio DECIMAL(10,2) NOT NULL,
	StockActual INT NOT NULL DEFAULT 0,
	StockMinimo INT NOT NULL DEFAULT 0,
	Activo BIT NOT NULL DEFAULT 1,
	Codigo NVARCHAR(30) NOT NULL
);

CREATE TABLE Pedido(
	PedidoId INT IDENTITY(1,1) PRIMARY KEY,
	ClienteId INT NOT NULL,
	NumeroPedido NVARCHAR(30) NOT NULL,
	Estado NVARCHAR(30) NOT NULL,
	FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
	FechaModificacion DATETIME NULL
);

CREATE TABLE DetallePedido(
	DetallePedidoId INT IDENTITY(1,1) PRIMARY KEY,
	PedidoId INT NOT NULL,
	ProductoId INT NOT NULL,
	Cantidad INT NOT NULL,
	SubTotal DECIMAL(10,2) NOT NULL,
	PrecioUnitario DECIMAL(10,2) NOT NULL
);

CREATE TABLE Entrega(
	EntregaId INT IDENTITY(1,1) PRIMARY KEY,
	UsuarioId INT NOT NULL,
	PedidoId INT NOT NULL,
	Observaciones NVARCHAR(255),
	FechaEntrega DATETIME NOT NULL,
	EstadoEntrega NVARCHAR(30) NOT NULL
);

CREATE TABLE MovimientoStock(
	MovimientoId INT IDENTITY(1,1) PRIMARY KEY,
	UsuarioId INT NOT NULL,
	ProductoId INT NOT NULL,
	Fecha DATETIME NOT NULL DEFAULT GETDATE(),
	Cantidad INT NOT NULL,
	Observaciones NVARCHAR(255),
	TipoMovimiento NVARCHAR(20) NOT NULL,
	Motivo NVARCHAR(100)
);
